//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ch.tutteli.taskscheduler.test.Soap12 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.tutteli.ch/types", ConfigurationName="Soap12.ISyncReply")]
    public interface ISyncReply {
        
        // CODEGEN: Generating message contract since the operation PostOneTimeTask is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/PostOneTimeTask", ReplyAction="*")]
        ch.tutteli.taskscheduler.test.Soap12.PostOneTimeTaskResponse PostOneTimeTask(ch.tutteli.taskscheduler.test.Soap12.PostOneTimeTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/PostOneTimeTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PostOneTimeTaskResponse> PostOneTimeTaskAsync(ch.tutteli.taskscheduler.test.Soap12.PostOneTimeTaskRequest request);
        
        // CODEGEN: Generating message contract since the operation PostDailyTask is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/PostDailyTask", ReplyAction="*")]
        ch.tutteli.taskscheduler.test.Soap12.PostDailyTaskResponse PostDailyTask(ch.tutteli.taskscheduler.test.Soap12.PostDailyTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/PostDailyTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PostDailyTaskResponse> PostDailyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.PostDailyTaskRequest request);
        
        // CODEGEN: Generating message contract since the operation PostWeeklyTask is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/PostWeeklyTask", ReplyAction="*")]
        ch.tutteli.taskscheduler.test.Soap12.PostWeeklyTaskResponse PostWeeklyTask(ch.tutteli.taskscheduler.test.Soap12.PostWeeklyTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/PostWeeklyTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PostWeeklyTaskResponse> PostWeeklyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.PostWeeklyTaskRequest request);
        
        // CODEGEN: Generating message contract since the operation PostMonthlyTask is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/PostMonthlyTask", ReplyAction="*")]
        ch.tutteli.taskscheduler.test.Soap12.PostMonthlyTaskResponse PostMonthlyTask(ch.tutteli.taskscheduler.test.Soap12.PostMonthlyTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/PostMonthlyTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PostMonthlyTaskResponse> PostMonthlyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.PostMonthlyTaskRequest request);
        
        // CODEGEN: Generating message contract since the operation PutOneTimeTask is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/PutOneTimeTask", ReplyAction="*")]
        ch.tutteli.taskscheduler.test.Soap12.PutOneTimeTaskResponse PutOneTimeTask(ch.tutteli.taskscheduler.test.Soap12.PutOneTimeTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/PutOneTimeTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PutOneTimeTaskResponse> PutOneTimeTaskAsync(ch.tutteli.taskscheduler.test.Soap12.PutOneTimeTaskRequest request);
        
        // CODEGEN: Generating message contract since the operation PutDailyTask is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/PutDailyTask", ReplyAction="*")]
        ch.tutteli.taskscheduler.test.Soap12.PutDailyTaskResponse PutDailyTask(ch.tutteli.taskscheduler.test.Soap12.PutDailyTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/PutDailyTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PutDailyTaskResponse> PutDailyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.PutDailyTaskRequest request);
        
        // CODEGEN: Generating message contract since the operation PutWeeklyTask is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/PutWeeklyTask", ReplyAction="*")]
        ch.tutteli.taskscheduler.test.Soap12.PutWeeklyTaskResponse PutWeeklyTask(ch.tutteli.taskscheduler.test.Soap12.PutWeeklyTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/PutWeeklyTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PutWeeklyTaskResponse> PutWeeklyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.PutWeeklyTaskRequest request);
        
        // CODEGEN: Generating message contract since the operation PutMonthlyTask is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/PutMonthlyTask", ReplyAction="*")]
        ch.tutteli.taskscheduler.test.Soap12.PutMonthlyTaskResponse PutMonthlyTask(ch.tutteli.taskscheduler.test.Soap12.PutMonthlyTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/PutMonthlyTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PutMonthlyTaskResponse> PutMonthlyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.PutMonthlyTaskRequest request);
        
        // CODEGEN: Generating message contract since the operation DeleteOneTimeTask is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/DeleteOneTimeTask", ReplyAction="*")]
        ch.tutteli.taskscheduler.test.Soap12.DeleteOneTimeTaskResponse DeleteOneTimeTask(ch.tutteli.taskscheduler.test.Soap12.DeleteOneTimeTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/DeleteOneTimeTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.DeleteOneTimeTaskResponse> DeleteOneTimeTaskAsync(ch.tutteli.taskscheduler.test.Soap12.DeleteOneTimeTaskRequest request);
        
        // CODEGEN: Generating message contract since the operation DeleteDailyTask is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/DeleteDailyTask", ReplyAction="*")]
        ch.tutteli.taskscheduler.test.Soap12.DeleteDailyTaskResponse DeleteDailyTask(ch.tutteli.taskscheduler.test.Soap12.DeleteDailyTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/DeleteDailyTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.DeleteDailyTaskResponse> DeleteDailyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.DeleteDailyTaskRequest request);
        
        // CODEGEN: Generating message contract since the operation DeleteWeeklyTask is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/DeleteWeeklyTask", ReplyAction="*")]
        ch.tutteli.taskscheduler.test.Soap12.DeleteWeeklyTaskResponse DeleteWeeklyTask(ch.tutteli.taskscheduler.test.Soap12.DeleteWeeklyTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/DeleteWeeklyTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.DeleteWeeklyTaskResponse> DeleteWeeklyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.DeleteWeeklyTaskRequest request);
        
        // CODEGEN: Generating message contract since the operation DeleteMonthlyTask is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/DeleteMonthlyTask", ReplyAction="*")]
        ch.tutteli.taskscheduler.test.Soap12.DeleteMonthlyTaskResponse DeleteMonthlyTask(ch.tutteli.taskscheduler.test.Soap12.DeleteMonthlyTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.servicestack.net/types/DeleteMonthlyTask", ReplyAction="*")]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.DeleteMonthlyTaskResponse> DeleteMonthlyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.DeleteMonthlyTaskRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostOneTimeTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.PostOneTimeTask PostOneTimeTask;
        
        public PostOneTimeTaskRequest() {
        }
        
        public PostOneTimeTaskRequest(ch.tutteli.taskscheduler.requests.PostOneTimeTask PostOneTimeTask) {
            this.PostOneTimeTask = PostOneTimeTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostOneTimeTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostOneTimeTaskResponse", Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.PostOneTimeTaskResponse PostOneTimeTaskResponse1;
        
        public PostOneTimeTaskResponse() {
        }
        
        public PostOneTimeTaskResponse(ch.tutteli.taskscheduler.requests.PostOneTimeTaskResponse PostOneTimeTaskResponse1) {
            this.PostOneTimeTaskResponse1 = PostOneTimeTaskResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostDailyTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.PostDailyTask PostDailyTask;
        
        public PostDailyTaskRequest() {
        }
        
        public PostDailyTaskRequest(ch.tutteli.taskscheduler.requests.PostDailyTask PostDailyTask) {
            this.PostDailyTask = PostDailyTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostDailyTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostDailyTaskResponse", Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.PostDailyTaskResponse PostDailyTaskResponse1;
        
        public PostDailyTaskResponse() {
        }
        
        public PostDailyTaskResponse(ch.tutteli.taskscheduler.requests.PostDailyTaskResponse PostDailyTaskResponse1) {
            this.PostDailyTaskResponse1 = PostDailyTaskResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostWeeklyTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.PostWeeklyTask PostWeeklyTask;
        
        public PostWeeklyTaskRequest() {
        }
        
        public PostWeeklyTaskRequest(ch.tutteli.taskscheduler.requests.PostWeeklyTask PostWeeklyTask) {
            this.PostWeeklyTask = PostWeeklyTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostWeeklyTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostWeeklyTaskResponse", Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.PostWeeklyTaskResponse PostWeeklyTaskResponse1;
        
        public PostWeeklyTaskResponse() {
        }
        
        public PostWeeklyTaskResponse(ch.tutteli.taskscheduler.requests.PostWeeklyTaskResponse PostWeeklyTaskResponse1) {
            this.PostWeeklyTaskResponse1 = PostWeeklyTaskResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostMonthlyTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.PostMonthlyTask PostMonthlyTask;
        
        public PostMonthlyTaskRequest() {
        }
        
        public PostMonthlyTaskRequest(ch.tutteli.taskscheduler.requests.PostMonthlyTask PostMonthlyTask) {
            this.PostMonthlyTask = PostMonthlyTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostMonthlyTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PostMonthlyTaskResponse", Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.PostMonthlyTaskResponse PostMonthlyTaskResponse1;
        
        public PostMonthlyTaskResponse() {
        }
        
        public PostMonthlyTaskResponse(ch.tutteli.taskscheduler.requests.PostMonthlyTaskResponse PostMonthlyTaskResponse1) {
            this.PostMonthlyTaskResponse1 = PostMonthlyTaskResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutOneTimeTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.PutOneTimeTask PutOneTimeTask;
        
        public PutOneTimeTaskRequest() {
        }
        
        public PutOneTimeTaskRequest(ch.tutteli.taskscheduler.requests.PutOneTimeTask PutOneTimeTask) {
            this.PutOneTimeTask = PutOneTimeTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutOneTimeTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutOneTimeTaskResponse", Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.PutOneTimeTaskResponse PutOneTimeTaskResponse1;
        
        public PutOneTimeTaskResponse() {
        }
        
        public PutOneTimeTaskResponse(ch.tutteli.taskscheduler.requests.PutOneTimeTaskResponse PutOneTimeTaskResponse1) {
            this.PutOneTimeTaskResponse1 = PutOneTimeTaskResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutDailyTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.PutDailyTask PutDailyTask;
        
        public PutDailyTaskRequest() {
        }
        
        public PutDailyTaskRequest(ch.tutteli.taskscheduler.requests.PutDailyTask PutDailyTask) {
            this.PutDailyTask = PutDailyTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutDailyTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutDailyTaskResponse", Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.PutDailyTaskResponse PutDailyTaskResponse1;
        
        public PutDailyTaskResponse() {
        }
        
        public PutDailyTaskResponse(ch.tutteli.taskscheduler.requests.PutDailyTaskResponse PutDailyTaskResponse1) {
            this.PutDailyTaskResponse1 = PutDailyTaskResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutWeeklyTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.PutWeeklyTask PutWeeklyTask;
        
        public PutWeeklyTaskRequest() {
        }
        
        public PutWeeklyTaskRequest(ch.tutteli.taskscheduler.requests.PutWeeklyTask PutWeeklyTask) {
            this.PutWeeklyTask = PutWeeklyTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutWeeklyTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutWeeklyTaskResponse", Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.PutWeeklyTaskResponse PutWeeklyTaskResponse1;
        
        public PutWeeklyTaskResponse() {
        }
        
        public PutWeeklyTaskResponse(ch.tutteli.taskscheduler.requests.PutWeeklyTaskResponse PutWeeklyTaskResponse1) {
            this.PutWeeklyTaskResponse1 = PutWeeklyTaskResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutMonthlyTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.PutMonthlyTask PutMonthlyTask;
        
        public PutMonthlyTaskRequest() {
        }
        
        public PutMonthlyTaskRequest(ch.tutteli.taskscheduler.requests.PutMonthlyTask PutMonthlyTask) {
            this.PutMonthlyTask = PutMonthlyTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutMonthlyTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutMonthlyTaskResponse", Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.PutMonthlyTaskResponse PutMonthlyTaskResponse1;
        
        public PutMonthlyTaskResponse() {
        }
        
        public PutMonthlyTaskResponse(ch.tutteli.taskscheduler.requests.PutMonthlyTaskResponse PutMonthlyTaskResponse1) {
            this.PutMonthlyTaskResponse1 = PutMonthlyTaskResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteOneTimeTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.DeleteOneTimeTask DeleteOneTimeTask;
        
        public DeleteOneTimeTaskRequest() {
        }
        
        public DeleteOneTimeTaskRequest(ch.tutteli.taskscheduler.requests.DeleteOneTimeTask DeleteOneTimeTask) {
            this.DeleteOneTimeTask = DeleteOneTimeTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteOneTimeTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteOneTimeTaskResponse", Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.DeleteOneTimeTaskResponse DeleteOneTimeTaskResponse1;
        
        public DeleteOneTimeTaskResponse() {
        }
        
        public DeleteOneTimeTaskResponse(ch.tutteli.taskscheduler.requests.DeleteOneTimeTaskResponse DeleteOneTimeTaskResponse1) {
            this.DeleteOneTimeTaskResponse1 = DeleteOneTimeTaskResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDailyTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.DeleteDailyTask DeleteDailyTask;
        
        public DeleteDailyTaskRequest() {
        }
        
        public DeleteDailyTaskRequest(ch.tutteli.taskscheduler.requests.DeleteDailyTask DeleteDailyTask) {
            this.DeleteDailyTask = DeleteDailyTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDailyTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDailyTaskResponse", Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.DeleteDailyTaskResponse DeleteDailyTaskResponse1;
        
        public DeleteDailyTaskResponse() {
        }
        
        public DeleteDailyTaskResponse(ch.tutteli.taskscheduler.requests.DeleteDailyTaskResponse DeleteDailyTaskResponse1) {
            this.DeleteDailyTaskResponse1 = DeleteDailyTaskResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteWeeklyTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.DeleteWeeklyTask DeleteWeeklyTask;
        
        public DeleteWeeklyTaskRequest() {
        }
        
        public DeleteWeeklyTaskRequest(ch.tutteli.taskscheduler.requests.DeleteWeeklyTask DeleteWeeklyTask) {
            this.DeleteWeeklyTask = DeleteWeeklyTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteWeeklyTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteWeeklyTaskResponse", Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.DeleteWeeklyTaskResponse DeleteWeeklyTaskResponse1;
        
        public DeleteWeeklyTaskResponse() {
        }
        
        public DeleteWeeklyTaskResponse(ch.tutteli.taskscheduler.requests.DeleteWeeklyTaskResponse DeleteWeeklyTaskResponse1) {
            this.DeleteWeeklyTaskResponse1 = DeleteWeeklyTaskResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMonthlyTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.DeleteMonthlyTask DeleteMonthlyTask;
        
        public DeleteMonthlyTaskRequest() {
        }
        
        public DeleteMonthlyTaskRequest(ch.tutteli.taskscheduler.requests.DeleteMonthlyTask DeleteMonthlyTask) {
            this.DeleteMonthlyTask = DeleteMonthlyTask;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteMonthlyTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteMonthlyTaskResponse", Namespace="http://schemas.tutteli.ch/types", Order=0)]
        public ch.tutteli.taskscheduler.requests.DeleteMonthlyTaskResponse DeleteMonthlyTaskResponse1;
        
        public DeleteMonthlyTaskResponse() {
        }
        
        public DeleteMonthlyTaskResponse(ch.tutteli.taskscheduler.requests.DeleteMonthlyTaskResponse DeleteMonthlyTaskResponse1) {
            this.DeleteMonthlyTaskResponse1 = DeleteMonthlyTaskResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISyncReplyChannel : ch.tutteli.taskscheduler.test.Soap12.ISyncReply, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SyncReplyClient : System.ServiceModel.ClientBase<ch.tutteli.taskscheduler.test.Soap12.ISyncReply>, ch.tutteli.taskscheduler.test.Soap12.ISyncReply {
        
        public SyncReplyClient() {
        }
        
        public SyncReplyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SyncReplyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncReplyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncReplyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ch.tutteli.taskscheduler.test.Soap12.PostOneTimeTaskResponse ch.tutteli.taskscheduler.test.Soap12.ISyncReply.PostOneTimeTask(ch.tutteli.taskscheduler.test.Soap12.PostOneTimeTaskRequest request) {
            return base.Channel.PostOneTimeTask(request);
        }
        
        public ch.tutteli.taskscheduler.requests.PostOneTimeTaskResponse PostOneTimeTask(ch.tutteli.taskscheduler.requests.PostOneTimeTask PostOneTimeTask1) {
            ch.tutteli.taskscheduler.test.Soap12.PostOneTimeTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.PostOneTimeTaskRequest();
            inValue.PostOneTimeTask = PostOneTimeTask1;
            ch.tutteli.taskscheduler.test.Soap12.PostOneTimeTaskResponse retVal = ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).PostOneTimeTask(inValue);
            return retVal.PostOneTimeTaskResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PostOneTimeTaskResponse> ch.tutteli.taskscheduler.test.Soap12.ISyncReply.PostOneTimeTaskAsync(ch.tutteli.taskscheduler.test.Soap12.PostOneTimeTaskRequest request) {
            return base.Channel.PostOneTimeTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PostOneTimeTaskResponse> PostOneTimeTaskAsync(ch.tutteli.taskscheduler.requests.PostOneTimeTask PostOneTimeTask) {
            ch.tutteli.taskscheduler.test.Soap12.PostOneTimeTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.PostOneTimeTaskRequest();
            inValue.PostOneTimeTask = PostOneTimeTask;
            return ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).PostOneTimeTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ch.tutteli.taskscheduler.test.Soap12.PostDailyTaskResponse ch.tutteli.taskscheduler.test.Soap12.ISyncReply.PostDailyTask(ch.tutteli.taskscheduler.test.Soap12.PostDailyTaskRequest request) {
            return base.Channel.PostDailyTask(request);
        }
        
        public ch.tutteli.taskscheduler.requests.PostDailyTaskResponse PostDailyTask(ch.tutteli.taskscheduler.requests.PostDailyTask PostDailyTask1) {
            ch.tutteli.taskscheduler.test.Soap12.PostDailyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.PostDailyTaskRequest();
            inValue.PostDailyTask = PostDailyTask1;
            ch.tutteli.taskscheduler.test.Soap12.PostDailyTaskResponse retVal = ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).PostDailyTask(inValue);
            return retVal.PostDailyTaskResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PostDailyTaskResponse> ch.tutteli.taskscheduler.test.Soap12.ISyncReply.PostDailyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.PostDailyTaskRequest request) {
            return base.Channel.PostDailyTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PostDailyTaskResponse> PostDailyTaskAsync(ch.tutteli.taskscheduler.requests.PostDailyTask PostDailyTask) {
            ch.tutteli.taskscheduler.test.Soap12.PostDailyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.PostDailyTaskRequest();
            inValue.PostDailyTask = PostDailyTask;
            return ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).PostDailyTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ch.tutteli.taskscheduler.test.Soap12.PostWeeklyTaskResponse ch.tutteli.taskscheduler.test.Soap12.ISyncReply.PostWeeklyTask(ch.tutteli.taskscheduler.test.Soap12.PostWeeklyTaskRequest request) {
            return base.Channel.PostWeeklyTask(request);
        }
        
        public ch.tutteli.taskscheduler.requests.PostWeeklyTaskResponse PostWeeklyTask(ch.tutteli.taskscheduler.requests.PostWeeklyTask PostWeeklyTask1) {
            ch.tutteli.taskscheduler.test.Soap12.PostWeeklyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.PostWeeklyTaskRequest();
            inValue.PostWeeklyTask = PostWeeklyTask1;
            ch.tutteli.taskscheduler.test.Soap12.PostWeeklyTaskResponse retVal = ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).PostWeeklyTask(inValue);
            return retVal.PostWeeklyTaskResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PostWeeklyTaskResponse> ch.tutteli.taskscheduler.test.Soap12.ISyncReply.PostWeeklyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.PostWeeklyTaskRequest request) {
            return base.Channel.PostWeeklyTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PostWeeklyTaskResponse> PostWeeklyTaskAsync(ch.tutteli.taskscheduler.requests.PostWeeklyTask PostWeeklyTask) {
            ch.tutteli.taskscheduler.test.Soap12.PostWeeklyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.PostWeeklyTaskRequest();
            inValue.PostWeeklyTask = PostWeeklyTask;
            return ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).PostWeeklyTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ch.tutteli.taskscheduler.test.Soap12.PostMonthlyTaskResponse ch.tutteli.taskscheduler.test.Soap12.ISyncReply.PostMonthlyTask(ch.tutteli.taskscheduler.test.Soap12.PostMonthlyTaskRequest request) {
            return base.Channel.PostMonthlyTask(request);
        }
        
        public ch.tutteli.taskscheduler.requests.PostMonthlyTaskResponse PostMonthlyTask(ch.tutteli.taskscheduler.requests.PostMonthlyTask PostMonthlyTask1) {
            ch.tutteli.taskscheduler.test.Soap12.PostMonthlyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.PostMonthlyTaskRequest();
            inValue.PostMonthlyTask = PostMonthlyTask1;
            ch.tutteli.taskscheduler.test.Soap12.PostMonthlyTaskResponse retVal = ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).PostMonthlyTask(inValue);
            return retVal.PostMonthlyTaskResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PostMonthlyTaskResponse> ch.tutteli.taskscheduler.test.Soap12.ISyncReply.PostMonthlyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.PostMonthlyTaskRequest request) {
            return base.Channel.PostMonthlyTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PostMonthlyTaskResponse> PostMonthlyTaskAsync(ch.tutteli.taskscheduler.requests.PostMonthlyTask PostMonthlyTask) {
            ch.tutteli.taskscheduler.test.Soap12.PostMonthlyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.PostMonthlyTaskRequest();
            inValue.PostMonthlyTask = PostMonthlyTask;
            return ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).PostMonthlyTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ch.tutteli.taskscheduler.test.Soap12.PutOneTimeTaskResponse ch.tutteli.taskscheduler.test.Soap12.ISyncReply.PutOneTimeTask(ch.tutteli.taskscheduler.test.Soap12.PutOneTimeTaskRequest request) {
            return base.Channel.PutOneTimeTask(request);
        }
        
        public ch.tutteli.taskscheduler.requests.PutOneTimeTaskResponse PutOneTimeTask(ch.tutteli.taskscheduler.requests.PutOneTimeTask PutOneTimeTask1) {
            ch.tutteli.taskscheduler.test.Soap12.PutOneTimeTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.PutOneTimeTaskRequest();
            inValue.PutOneTimeTask = PutOneTimeTask1;
            ch.tutteli.taskscheduler.test.Soap12.PutOneTimeTaskResponse retVal = ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).PutOneTimeTask(inValue);
            return retVal.PutOneTimeTaskResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PutOneTimeTaskResponse> ch.tutteli.taskscheduler.test.Soap12.ISyncReply.PutOneTimeTaskAsync(ch.tutteli.taskscheduler.test.Soap12.PutOneTimeTaskRequest request) {
            return base.Channel.PutOneTimeTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PutOneTimeTaskResponse> PutOneTimeTaskAsync(ch.tutteli.taskscheduler.requests.PutOneTimeTask PutOneTimeTask) {
            ch.tutteli.taskscheduler.test.Soap12.PutOneTimeTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.PutOneTimeTaskRequest();
            inValue.PutOneTimeTask = PutOneTimeTask;
            return ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).PutOneTimeTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ch.tutteli.taskscheduler.test.Soap12.PutDailyTaskResponse ch.tutteli.taskscheduler.test.Soap12.ISyncReply.PutDailyTask(ch.tutteli.taskscheduler.test.Soap12.PutDailyTaskRequest request) {
            return base.Channel.PutDailyTask(request);
        }
        
        public ch.tutteli.taskscheduler.requests.PutDailyTaskResponse PutDailyTask(ch.tutteli.taskscheduler.requests.PutDailyTask PutDailyTask1) {
            ch.tutteli.taskscheduler.test.Soap12.PutDailyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.PutDailyTaskRequest();
            inValue.PutDailyTask = PutDailyTask1;
            ch.tutteli.taskscheduler.test.Soap12.PutDailyTaskResponse retVal = ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).PutDailyTask(inValue);
            return retVal.PutDailyTaskResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PutDailyTaskResponse> ch.tutteli.taskscheduler.test.Soap12.ISyncReply.PutDailyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.PutDailyTaskRequest request) {
            return base.Channel.PutDailyTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PutDailyTaskResponse> PutDailyTaskAsync(ch.tutteli.taskscheduler.requests.PutDailyTask PutDailyTask) {
            ch.tutteli.taskscheduler.test.Soap12.PutDailyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.PutDailyTaskRequest();
            inValue.PutDailyTask = PutDailyTask;
            return ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).PutDailyTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ch.tutteli.taskscheduler.test.Soap12.PutWeeklyTaskResponse ch.tutteli.taskscheduler.test.Soap12.ISyncReply.PutWeeklyTask(ch.tutteli.taskscheduler.test.Soap12.PutWeeklyTaskRequest request) {
            return base.Channel.PutWeeklyTask(request);
        }
        
        public ch.tutteli.taskscheduler.requests.PutWeeklyTaskResponse PutWeeklyTask(ch.tutteli.taskscheduler.requests.PutWeeklyTask PutWeeklyTask1) {
            ch.tutteli.taskscheduler.test.Soap12.PutWeeklyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.PutWeeklyTaskRequest();
            inValue.PutWeeklyTask = PutWeeklyTask1;
            ch.tutteli.taskscheduler.test.Soap12.PutWeeklyTaskResponse retVal = ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).PutWeeklyTask(inValue);
            return retVal.PutWeeklyTaskResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PutWeeklyTaskResponse> ch.tutteli.taskscheduler.test.Soap12.ISyncReply.PutWeeklyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.PutWeeklyTaskRequest request) {
            return base.Channel.PutWeeklyTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PutWeeklyTaskResponse> PutWeeklyTaskAsync(ch.tutteli.taskscheduler.requests.PutWeeklyTask PutWeeklyTask) {
            ch.tutteli.taskscheduler.test.Soap12.PutWeeklyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.PutWeeklyTaskRequest();
            inValue.PutWeeklyTask = PutWeeklyTask;
            return ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).PutWeeklyTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ch.tutteli.taskscheduler.test.Soap12.PutMonthlyTaskResponse ch.tutteli.taskscheduler.test.Soap12.ISyncReply.PutMonthlyTask(ch.tutteli.taskscheduler.test.Soap12.PutMonthlyTaskRequest request) {
            return base.Channel.PutMonthlyTask(request);
        }
        
        public ch.tutteli.taskscheduler.requests.PutMonthlyTaskResponse PutMonthlyTask(ch.tutteli.taskscheduler.requests.PutMonthlyTask PutMonthlyTask1) {
            ch.tutteli.taskscheduler.test.Soap12.PutMonthlyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.PutMonthlyTaskRequest();
            inValue.PutMonthlyTask = PutMonthlyTask1;
            ch.tutteli.taskscheduler.test.Soap12.PutMonthlyTaskResponse retVal = ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).PutMonthlyTask(inValue);
            return retVal.PutMonthlyTaskResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PutMonthlyTaskResponse> ch.tutteli.taskscheduler.test.Soap12.ISyncReply.PutMonthlyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.PutMonthlyTaskRequest request) {
            return base.Channel.PutMonthlyTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.PutMonthlyTaskResponse> PutMonthlyTaskAsync(ch.tutteli.taskscheduler.requests.PutMonthlyTask PutMonthlyTask) {
            ch.tutteli.taskscheduler.test.Soap12.PutMonthlyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.PutMonthlyTaskRequest();
            inValue.PutMonthlyTask = PutMonthlyTask;
            return ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).PutMonthlyTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ch.tutteli.taskscheduler.test.Soap12.DeleteOneTimeTaskResponse ch.tutteli.taskscheduler.test.Soap12.ISyncReply.DeleteOneTimeTask(ch.tutteli.taskscheduler.test.Soap12.DeleteOneTimeTaskRequest request) {
            return base.Channel.DeleteOneTimeTask(request);
        }
        
        public ch.tutteli.taskscheduler.requests.DeleteOneTimeTaskResponse DeleteOneTimeTask(ch.tutteli.taskscheduler.requests.DeleteOneTimeTask DeleteOneTimeTask1) {
            ch.tutteli.taskscheduler.test.Soap12.DeleteOneTimeTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.DeleteOneTimeTaskRequest();
            inValue.DeleteOneTimeTask = DeleteOneTimeTask1;
            ch.tutteli.taskscheduler.test.Soap12.DeleteOneTimeTaskResponse retVal = ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).DeleteOneTimeTask(inValue);
            return retVal.DeleteOneTimeTaskResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.DeleteOneTimeTaskResponse> ch.tutteli.taskscheduler.test.Soap12.ISyncReply.DeleteOneTimeTaskAsync(ch.tutteli.taskscheduler.test.Soap12.DeleteOneTimeTaskRequest request) {
            return base.Channel.DeleteOneTimeTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.DeleteOneTimeTaskResponse> DeleteOneTimeTaskAsync(ch.tutteli.taskscheduler.requests.DeleteOneTimeTask DeleteOneTimeTask) {
            ch.tutteli.taskscheduler.test.Soap12.DeleteOneTimeTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.DeleteOneTimeTaskRequest();
            inValue.DeleteOneTimeTask = DeleteOneTimeTask;
            return ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).DeleteOneTimeTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ch.tutteli.taskscheduler.test.Soap12.DeleteDailyTaskResponse ch.tutteli.taskscheduler.test.Soap12.ISyncReply.DeleteDailyTask(ch.tutteli.taskscheduler.test.Soap12.DeleteDailyTaskRequest request) {
            return base.Channel.DeleteDailyTask(request);
        }
        
        public ch.tutteli.taskscheduler.requests.DeleteDailyTaskResponse DeleteDailyTask(ch.tutteli.taskscheduler.requests.DeleteDailyTask DeleteDailyTask1) {
            ch.tutteli.taskscheduler.test.Soap12.DeleteDailyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.DeleteDailyTaskRequest();
            inValue.DeleteDailyTask = DeleteDailyTask1;
            ch.tutteli.taskscheduler.test.Soap12.DeleteDailyTaskResponse retVal = ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).DeleteDailyTask(inValue);
            return retVal.DeleteDailyTaskResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.DeleteDailyTaskResponse> ch.tutteli.taskscheduler.test.Soap12.ISyncReply.DeleteDailyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.DeleteDailyTaskRequest request) {
            return base.Channel.DeleteDailyTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.DeleteDailyTaskResponse> DeleteDailyTaskAsync(ch.tutteli.taskscheduler.requests.DeleteDailyTask DeleteDailyTask) {
            ch.tutteli.taskscheduler.test.Soap12.DeleteDailyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.DeleteDailyTaskRequest();
            inValue.DeleteDailyTask = DeleteDailyTask;
            return ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).DeleteDailyTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ch.tutteli.taskscheduler.test.Soap12.DeleteWeeklyTaskResponse ch.tutteli.taskscheduler.test.Soap12.ISyncReply.DeleteWeeklyTask(ch.tutteli.taskscheduler.test.Soap12.DeleteWeeklyTaskRequest request) {
            return base.Channel.DeleteWeeklyTask(request);
        }
        
        public ch.tutteli.taskscheduler.requests.DeleteWeeklyTaskResponse DeleteWeeklyTask(ch.tutteli.taskscheduler.requests.DeleteWeeklyTask DeleteWeeklyTask1) {
            ch.tutteli.taskscheduler.test.Soap12.DeleteWeeklyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.DeleteWeeklyTaskRequest();
            inValue.DeleteWeeklyTask = DeleteWeeklyTask1;
            ch.tutteli.taskscheduler.test.Soap12.DeleteWeeklyTaskResponse retVal = ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).DeleteWeeklyTask(inValue);
            return retVal.DeleteWeeklyTaskResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.DeleteWeeklyTaskResponse> ch.tutteli.taskscheduler.test.Soap12.ISyncReply.DeleteWeeklyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.DeleteWeeklyTaskRequest request) {
            return base.Channel.DeleteWeeklyTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.DeleteWeeklyTaskResponse> DeleteWeeklyTaskAsync(ch.tutteli.taskscheduler.requests.DeleteWeeklyTask DeleteWeeklyTask) {
            ch.tutteli.taskscheduler.test.Soap12.DeleteWeeklyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.DeleteWeeklyTaskRequest();
            inValue.DeleteWeeklyTask = DeleteWeeklyTask;
            return ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).DeleteWeeklyTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ch.tutteli.taskscheduler.test.Soap12.DeleteMonthlyTaskResponse ch.tutteli.taskscheduler.test.Soap12.ISyncReply.DeleteMonthlyTask(ch.tutteli.taskscheduler.test.Soap12.DeleteMonthlyTaskRequest request) {
            return base.Channel.DeleteMonthlyTask(request);
        }
        
        public ch.tutteli.taskscheduler.requests.DeleteMonthlyTaskResponse DeleteMonthlyTask(ch.tutteli.taskscheduler.requests.DeleteMonthlyTask DeleteMonthlyTask1) {
            ch.tutteli.taskscheduler.test.Soap12.DeleteMonthlyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.DeleteMonthlyTaskRequest();
            inValue.DeleteMonthlyTask = DeleteMonthlyTask1;
            ch.tutteli.taskscheduler.test.Soap12.DeleteMonthlyTaskResponse retVal = ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).DeleteMonthlyTask(inValue);
            return retVal.DeleteMonthlyTaskResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.DeleteMonthlyTaskResponse> ch.tutteli.taskscheduler.test.Soap12.ISyncReply.DeleteMonthlyTaskAsync(ch.tutteli.taskscheduler.test.Soap12.DeleteMonthlyTaskRequest request) {
            return base.Channel.DeleteMonthlyTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<ch.tutteli.taskscheduler.test.Soap12.DeleteMonthlyTaskResponse> DeleteMonthlyTaskAsync(ch.tutteli.taskscheduler.requests.DeleteMonthlyTask DeleteMonthlyTask) {
            ch.tutteli.taskscheduler.test.Soap12.DeleteMonthlyTaskRequest inValue = new ch.tutteli.taskscheduler.test.Soap12.DeleteMonthlyTaskRequest();
            inValue.DeleteMonthlyTask = DeleteMonthlyTask;
            return ((ch.tutteli.taskscheduler.test.Soap12.ISyncReply)(this)).DeleteMonthlyTaskAsync(inValue);
        }
    }
}
